server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: malrang-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kiwi1020/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        encrypt:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

encrypt:
  key: V2k@7g#eQ3rL!mT9